version: "3"
services:
  csvserver:
    image: "infracloudio/csvserver:latest"
    volumes:
      - ./inputFile:/csvserver/inputdata
    environment:
      CSVSERVER_BORDER: orange 
    ports:
      - "9393:9300"
  prometheus:
    image: "prom/prometheus:v2.22.0"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml 
    ports:
      - '9090:9090'
